### ISSUE TITLE
DEPRECATION: MarkupSafe is being installed using the legacy 'setup.py install' method

### ISSUE THREAD

**Issue by fenchu** [pallets/markupsafe#333] opened 2022-11-03 11:08 UTC
```
 DEPRECATION: MarkupSafe is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```
MarkupSafe==2.1.1
https://github.com/pypa/pip/issues/8559

**Comment by davidism** [comment] 2022-11-03 13:31
Duplicate of #327

**Closed by davidism** 2022-11-03 13:31 UTC

**Comment by ssbarnea** [comment] 2022-12-23 10:21
@davidism Any chance we will see this released? It is a shame that this project still uses archaic packaging. In fact I am wondering why it was not migrated to PEP-621 -- aka ditching both setup.py and setup.cfg?
