### ISSUE TITLE
Removal of soft_unicode has broken many packages

### ISSUE THREAD

**Issue by rosejn** [pallets/markupsafe#304] opened 2022-05-04 15:46 UTC
I just wanted to flag up that the removal of soft_unicode in a non-major release has broken a number of packages.  I ran into this trying to use the swagger api client generator swagger_to, which uses Jinja2 (as do many projects), but a quick google finds the AWS cli and many other packages are broken because of this change.  It seems like something that although deprecated was used a lot, and might have been best to remove in a new version so that existing dependencies aren't broken.

**Comment by davidism** [comment] 2022-05-04 15:47
Duplicate of https://github.com/pallets/markupsafe/issues/282

Please use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Closed by davidism** 2022-05-04 15:47 UTC

**Comment by Robert969696** [comment] 2022-05-11 21:48
I got exactly same issue. What is the potential fix?
