### ISSUE TITLE
Release 2.1 is Breaking for Jinja2<3.0

### ISSUE THREAD

**Issue by rmorshea** [pallets/markupsafe#283] opened 2022-02-18 05:55 UTC
```
pip install Jinja2<3.0
```

```python
Python 3.9.0 (default, Dec  4 2020, 20:11:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryan/Repositories/idom-team/idom/.nox/test_python_suite/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/ryan/Repositories/idom-team/idom/.nox/test_python_suite/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/ryan/Repositories/idom-team/idom/.nox/test_python_suite/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/ryan/Repositories/idom-team/idom/.nox/test_python_suite/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ryan/Repositories/idom-team/idom/.nox/test_python_suite/lib/python3.9/site-packages/markupsafe/__init__.py)
```

**Comment by rmorshea** [comment] 2022-02-18 05:57
You can just require `markupsafe<2.1` to work around this, but I figured I'd report in case this wasn't intentional or in case this is something that should be reported to Jinja instead.

**Comment by davidism** [comment] 2022-02-18 05:58
Duplicate of #282

**Closed by davidism** 2022-02-18 05:58 UTC
