### ISSUE TITLE
unable to install to windows 7

### ISSUE THREAD

**Issue by paolospane** [pallets/markupsafe#86] opened 2017-11-16 12:10 UTC
Dear all,

I'm not able to install markupSafe in windows7.  I ran the script: pip install markupsafe and i had the following output:

![image](https://user-images.githubusercontent.com/13947509/32890477-32a16bec-cacf-11e7-8ac9-5cb721610377.png)

It looks like it can not find the path or some the files.

Could you please support me?

Best,
Paolo

**Comment by rockbyo5** [comment] 2017-11-21 02:49
Im no expert, but you could try making sure wheel is up to date:
`pip install -U pip setuptools wheel`

**Comment by hugovk** [comment] 2017-11-29 08:40
It looks like it is trying to build the C code from source, which is never much fun on Windows.

See https://github.com/pallets/markupsafe/issues/45#issuecomment-335038182 -- prebuilt wheels will be available in the next release for Windows (from PR https://github.com/pallets/markupsafe/pull/65).

(You may be able to find prerelease wheels on AppVeyor, but I don't know what the URL is, https://ci.appveyor.com/project/pallets/markupsafe is 404.)

**Comment by davidism** [comment] 2018-10-21 01:40
Closing, appears to be a duplicate of #67, which was solved by updating pip and setuptools. Also should be solved by #45.

**Closed by davidism** 2018-10-21 01:40 UTC

**Comment by davidism** [comment] 2018-11-05 18:51
PyPI has wheels for MarkupSafe 1.1.0.
