### ISSUE TITLE
wheels for markupsafe

### ISSUE THREAD

**Issue by srkunze** [pallets/markupsafe#45] opened 2015-09-10 14:41 UTC
Do you consider providing Python wheels for markupsafe? cf. http://pythonwheels.com/

**Comment by graingert** [comment] 2016-11-07 15:09
@pallets you should separate out the binary speedups from the main source universal wheel

**Comment by davidism** [comment] 2016-11-07 18:22
There's not much point in universal wheels beyond a minor size reduction and a green bar on that site.  In this case it would also give a false sense of what's happening.

I *am* working on figuring this out, but creating a comprehensive set of wheels is not well documented, and is even harder when I only have access to Linux.

**Comment by graingert** [comment] 2016-11-07 18:24
@davidism the speedups are optional, so I'd argue it should be in an extras_require value.

**Comment by graingert** [comment] 2016-11-07 18:24
eg pip install markupsafe[speedups]

**Comment by davidism** [comment] 2016-11-07 18:25
That's not the plan.  Other libraries like SQLAlchemy bundle their speedups as well.  The speedups are optional now too, if they can't compile the pure Python version is substituded without error.

**Comment by graingert** [comment] 2016-11-07 18:51
@davidism Twisted plan on using this approach for wheels: https://twistedmatrix.com/trac/ticket/7945

There are other advantages:  You'd only need to rebuild the wheels for speedups changes, which presumably happen less often than the rest of the package.

**Comment by graingert** [comment] 2016-11-07 18:53
SQLAlchemy is anti async/await and wheel so I don't think it's a good idea to follow their approach.

**Comment by mjpieters** [comment] 2016-11-07 21:40
Why produce a universal wheel at all? That's not more useful than the current distribution formats for this project.

If you are going to distribute wheels, then people are going to expect those to include the compiled C speed-ups. That's the real strength of wheels; to distribute pre-built binaries.

**Comment by davidism** [comment] 2017-02-09 09:38
We need Linux, Mac, and Windows; 32 and 64 bit; 2.6, 2.7, 3.3, 3.4, 3.5, and 3.6 builds. Travis can handle Linux (manylinux) and Mac; Appveyor does Windows. If anyone has experience setting these up contributions are welcome. Otherwise I'll keep working away at it when I have time.

**Comment by graingert** [comment] 2017-02-09 09:47
@mjpieters @davidism wheels are much faster to install (even than pure python sdists), and when you're installing hundreds of packages it makes a big difference.

**Comment by graingert** [comment] 2017-02-09 09:49
Also the markupsafe C module is only an optional speedup

**Comment by mitsuhiko** [comment] 2017-02-09 09:51
It's a massive pain to set up these things. If someone wants to do it, you can use getsentry/libsourcemap and getsentry/symsynd as a point of reference.

**Comment by graingert** [comment] 2017-02-09 10:00
@mitsuhiko what makes you think that nobody would be able to install the speedups if they were a separate package?

**Comment by mitsuhiko** [comment] 2017-02-09 10:04
The entire point of markupsafe is the speedups. The only reason we have a fallback is because of user friendliness. Nobody should ever use markupsafe without the speedups. Feature flags barely work, definitely do not work with wheels and a `markupsafe-fast` as a separate package most people will miss entirely. So definitely not a fan.

**Comment by graingert** [comment] 2017-02-09 10:06
@mitsuhiko I was actually thinking that you'd have the speedups in `pip install markupsafe` which would depend on the pure python in `markupsafe-slow`

**Comment by mitsuhiko** [comment] 2017-02-09 10:08
Since this hypothetical `markupsafe` does not exist right now (we do not build binaries yet) not sure what the value in this is. If anything this will make everything more complex now because what if people have dependencies to `markupsafe` but you only have `markupsafe-slow` installed? Eg: Jinja2 and Flask depend on markupsafe.

Also this will shave off basically no time since pip caches wheels locally anyways.

**Comment by graingert** [comment] 2017-02-09 10:12
Yeah it would not be a great improvement but it means that the pure python would not go stale when a new binary was published

**Comment by mitsuhiko** [comment] 2017-02-09 10:13
I just don't get what exactly this is supposed to solve. MarkupSafe installs very quickly if there is no c compiler on the system. How much time are we talking about here?

**Comment by graingert** [comment] 2017-02-09 10:40
@mitsuhiko https://github.com/braintree/braintree_python/pull/76#issuecomment-257435553

**Comment by mitsuhiko** [comment] 2017-02-09 10:44
@graingert not sure how that is in any way relevant to the installation speed of markupsafe.

**Comment by graingert** [comment] 2017-02-09 10:44
> In case you're wondering the difference that wheels can make:

**Comment by graingert** [comment] 2017-02-09 10:44
not sure if I linked to the correct comment, but it should be one benchmarking a pure-python wheel

**Comment by mitsuhiko** [comment] 2017-02-09 10:50
So from what I can tell downloading + installing markupsafe without compiling here takes 1.1 seconds with compiling 2 seconds and downloading and installing markupsafe from a wheel takes 0.8 seconds. That does not seem at all important in the grand scheme of things.

Even more so now that pip caches wheels locally so once you have installed markupsafe once it will just reused the wheel from the cache.

**Comment by mitsuhiko** [comment] 2017-02-09 10:54
I can't reproduce the 1.1sec vs 0.8 sec even. They are more or less the same when run multiple times. That also makes sense because there is barely any sourcecode in markupsafe and few files.

**Comment by m-messiah** [comment] 2017-03-07 15:28
You said markupsafe installs quickly now, but you missed one fact for current master - it installs from github, instead of PyPi. So, while existence of wheels is a question, PyPi packages has big advantages after git:
+ quick version check, without downloading 
+ declarative requirements without reinstalling
+ devpi proxy for PyPI

So, although  there is no wheels, I think we still need PyPi release.

**Comment by mitsuhiko** [comment] 2017-03-07 15:33
I pushed up 1.0.

**Comment by m-messiah** [comment] 2017-03-07 15:55
Thanks @mitsuhiko !

**Comment by edmorley** [comment] 2017-07-19 18:45
Fwiw the performance improvement is not the only benefit, distributing as a wheel also:
* Allows the wheel cache to work even when using the new pip hash-checking mode
* Allows tools to statically inspect the package metadata without having to execute untrusted code.

If it helps, there's now a demo project for using [manylinux1](https://www.python.org/dev/peps/pep-0513/):
https://github.com/pypa/python-manylinux-demo

**Comment by davidism** [comment] 2017-07-19 19:46
The manylinux example has been around for a while, and is great. The issue is figuring out the huge matrix of Mac and Windows builds, which have very sparse documentation as far as I can find. https://github.com/pallets/markupsafe/issues/45#issuecomment-278592143  I don't want to release *a* wheel just to satisfy a green check on a website, I want to release a *good set* of wheels to actually be useful.

Paul Kehrer has a good talk about the permutations to keep in mind: https://youtu.be/-j4lolWgD6Q?t=16m33s.

#65 adds support for building Windows wheels, but I have not had time to review it. If anyone is familiar and wants to help review, that would be great. I would also appreciate any help getting Travis set up to produce Mac builds.

**Comment by edmorley** [comment] 2017-07-19 20:07
I agree it would be good to cover all platforms, however there's no disadvantage to rolling out wheels builds incrementally for certain platforms first - especially given that certain combinations (eg linux) will cover a significant proportion of downloads :-)

**Comment by davidism** [comment] 2017-07-19 20:17
I'm not very concerned with Linux since the extension requires nothing besides a compiler and the Python headers.

**Comment by davidism** [comment] 2017-07-27 13:49
https://github.com/joerick/cibuildwheel

**Comment by pombredanne** [comment] 2017-09-25 15:16
@davidism if this can help I have CI repos I use specificaly to build wheel on Linux/macOS and Windows at https://github.com/pombreda/thirdparty and https://github.com/pombreda/thirdparty-manylinux/ 
I will add markupsafe and kick in builds for 1.0 and the latest master.

**Comment by pombredanne** [comment] 2017-09-25 15:21
@edmorley FWIW if this can help, you can use a check or tarbal and run `python setup.py --without-speedups bdist_wheel` to build a wheel in `dist/`without the speedups locally.

@davidism  unrelated but the setuptools `Feature` feature used for the optional speedups is marked as deprecated in the latest setuptools code.

**Comment by davidism** [comment] 2017-09-25 16:12
From what I remember, it's gone back and forth a few times. I think the alternative is `Extension`, but I'm not familiar with the differences.

**Comment by davidism** [comment] 2017-10-08 21:00
Thanks to @dougthor42 #65 we now have Windows wheels for 2.6-3.6 32/64.

**Comment by ddanilko** [comment] 2018-07-17 08:49
Could someone please upload a wheel for MarkupSafe 1.0?
I am having issue #86 due to pip trying to install from .tar.gz
I build a wheel from sources (it succeeded with some warnings that speedups could not have been built) and I managed to install it but I would rather not host it myself.

**Closed** 2018-11-02 17:13 UTC

**Comment by pombredanne** [comment] 2018-11-02 22:33
thank you!

**Comment by davidism** [comment] 2018-11-05 18:52
PyPI has wheels for MarkupSafe 1.1.0.
