### ISSUE TITLE
ImportError:  cannot import 'soft_unicode' from 'markupsafe' 2.1.0

### ISSUE THREAD

**Issue by gvarnell** [pallets/markupsafe#288] opened 2022-02-18 15:33 UTC
Since release 2.1.0, all builds are failing.  

cannot import name 'soft_unicode' from 'markupsafe'

pip install markupsafe

**Comment by davidism** [comment] 2022-02-18 15:41
Duplicate of #282 

You are using an unsupported version of the project, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Closed** 2022-02-18 15:41 UTC
